adding gate

diff --git a/.github/workflows/trivy_scan.yml b/.github/workflows/trivy_scan.yml
--- a/.github/workflows/trivy_scan.yml
+++ b/.github/workflows/trivy_scan.yml
@@ -31,7 +31,7 @@ jobs:
         run: |
           trivy image --format json -o trivy-results.json myapp:latest
 
-          trivy image --severity HIGH,CRITICAL --exit-code 0 --format template --template "@contrib/html.tpl" -o interactive_report.html myapp:latest
+          trivy image --severity HIGH,CRITICAL --exit-code 1 --format template --template "@contrib/html.tpl" -o interactive_report.html myapp:latest
         
 
       - name: Generate Visual Job Summary
@@ -58,5 +58,12 @@ jobs:
         with:
           name: trivy-image-report
           path: interactive_report.html
+
+      - name: IF Fail
+        run: |
+          if [ "$CRITICAL_COUNT" -gt 0 ] || [ "$HIGH_COUNT" -gt 0 ]; then
+            echo "Security Gate Failed!"
+            exit 1 
+          fi
 
       
